### ISSUE TITLE
代码里有一处涉及隐私，请帮忙删除

### ISSUE THREAD

**Issue by yoyofx** [Mr-zhang4/wechat#1]
[grafana-alert-web-hook-master/](https://github.com/Mr-zhang4/wechat/blob/master/grafana-alert-web-hook-master/config.yml)

alert:
  test: 
  后面内容需要清空，麻烦了

**Comment by yoyofx** [comment]
感谢

**Comment by Mr-zhang4** [comment]
收到，谢谢您。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YoyoFx ***@***.***&gt;
发送时间: 2022年5月9日 11:19
收件人: Mr-zhang4/wechat ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Mr-zhang4/wechat] 代码里有一处涉及隐私，请帮忙删除 (Issue #1)





 
grafana-alert-web-hook-master/
 
alert:
 test:
 后面内容需要清空，麻烦了
